apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: login-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: "login.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: login-app-service
                port:
                  number: 80 # The port defined in the Service(service port)
